// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvxaouuggimcwyvjzqpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eGFvdXVnZ2ltY3d5dmp6cXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTAyNjQsImV4cCI6MjA3NDI2NjI2NH0.XBW99yD-mux1kaB3bmrB6e19EPtCqS2kkC4FphjaosA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});